# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: apache.releases.https # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Configure Maven Settings
      id: configure-maven
      uses: DamianReeves/write-file-action@v1.2
      with:
        path: ${{ github.workspace }}/settings.xml
        contents: ${{ secrets.MVN_SETTINGS }}
        write-mode: overwrite

    - name: Build and Release Artifact
      id: release-jar
      run: mvn clean deploy -Drevision=${{ github.event.release.tag_name }} -s $GITHUB_WORKSPACE/settings.xml -f pom.xml

    - name: Slack Report Failure
      if: failure()
      # https://github.com/marketplace/actions/action-slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        author_name: ${{ github.workflow }}
        fields: repo,message,commit,author,job,workflow
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
