name: Maven Package

on:
  pull_request_target:
    types: ['opened', 'reopened', 'synchronize', 'ready_for_review']
    branches:
      - '**'
    paths:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Test and Build Artifact
      id: build
      run:
        mvn package \
          -Drevision=${{ github.event.pull_request.head.sha }} \
          -U -B -ff -fae \
          -f pom.xml
